name: CI

on:
  - push
  - pull_request

jobs:
  checks:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Install Dependencies
        run: npm ci
      - name: Check Dependencies
        run: npm audit
      - name: Lint Project
        run: npm run lint
      - name: Build with Typescript
        run: npm run build
